name: Household Tool
slug: household_tool
version: 0.4.1
description: Internes Haushalts-Intranet mit Projekte-App und File-Sharing.
startup: services
boot: auto
arch:
  - aarch64
  - amd64
init: false
webui: http://[HOST]:[PORT:8099]
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web UI
map: []
options:
  admin_username: admin
  admin_password: ""
schema:
  admin_username: str
  admin_password: password?
